development:
  adapter: postgresql
  database: disclosed_web_development
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  encoding: unicode
  pool: 5
test:
  adapter: postgresql
  database: disclosed_web_test
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  encoding: unicode
  pool: 5
